FROM python:3-alpine

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt
RUN apk --update add openssl ca-certificates py-openssl wget bash linux-headers \
  && pip install --upgrade pip \
  && pip install --upgrade pipenv\
  && pip install --upgrade -r /tmp/requirements.txt\
  && apk del build-dependencies

COPY . /app
ENV FLASK_APP=server/__init__.py
CMD ["python", "manage.py", "start", "0.0.0.0:3000"]
